apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: apigateway
  name: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apigateway
    spec:
      containers:
      - image: apigateway
        imagePullPolicy: "Never"
        name: apigateway
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: apigateway
  name: apigateway
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: apigateway
  type: ClusterIP
status:
  loadBalancer: {}
